# Dockerfile.dev
FROM node:20

WORKDIR /app

# Angular CLI globálisan
RUN npm install -g @angular/cli

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Expose Angular dev port
EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]

